CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT NOT NULL,
	second_name TEXT NOT NULL,
	surname TEXT NOT NULL,
	username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
	is_admin BOOLEAN
);

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	current_status TEXT NOT NULL,
	files TEXT NOT NULL,
	recipient INTEGER NOT NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
	FOREIGN KEY (author_id) REFERENCES user (id)
);
