CREATE TABLE IF NOT EXISTS user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  first_name TEXT UNIQUE NOT NULL,
	second_name TEXT UNIQUE NOT NULL,
	surname TEXT UNIQUE NOT NULL,
	username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
	is_admin BOOLEAN
);

CREATE TABLE IF NOT EXISTS task (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);